# Copyright 2020 The Google Java Format Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release ktfmt

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version number for this release."
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "zulu"
          cache: "maven"

      - name: Bump Version Number
        run: |
          mvn --no-transfer-progress versions:set versions:commit -DnewVersion="${{ github.event.inputs.version }}"
          git ls-files | grep -E '(pom.xml|MANIFEST.MF)$' | xargs git add
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git commit -m "Release ktfmt ${{ github.event.inputs.version }}"
          git tag "v${{ github.event.inputs.version }}"
          echo "TARGET_COMMITISH=$(git rev-parse HEAD)" >> $GITHUB_ENV
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/kageiit/ktfmt.git

      - name: Push tag
        run: |
          git push origin "v${{ github.event.inputs.version }}"

  build-native-image:
    name: "Build GraalVM native-image on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    needs: bump-version
    strategy:
      matrix:
        # Use "oldest" available ubuntu-* instead of -latest,
        # see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories;
        # due to https://github.com/google/google-java-format/issues/1072.
        os: [ubuntu-20.04, macos-latest]
    env:
        # NB: Must keep the keys in this inline JSON below in line with the os: above!
      SUFFIX: ${{fromJson('{"ubuntu-20.04":"linux-x86-64", "macos-latest":"darwin-arm64"}')[matrix.os]}}
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4
      - name: "Set up GraalVM"
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21"
          distribution: "graalvm-community"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: "true"
          cache: "maven"
      - name: Bump Version Number
        run: mvn --no-transfer-progress versions:set versions:commit -DnewVersion="${{ github.event.inputs.version }}"
      - name: "Native"
        run: mvn -Pnative -DskipTests package -pl core -am
      - name: "Move outputs"
        run: cp core/target/ktfmt ktfmt_${{ env.SUFFIX }}
      - name: "Upload native-image"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release upload "v${{ github.event.inputs.version }}" "ktfmt_${{ env.SUFFIX }}"
